In [1]:
import numpy as np
list1 = [4,8,10,12]
ar1 = np.array(list1)
print(ar1)


[ 4  8 10 12]


In [2]:
import numpy as np
list1 = [1,4,8,10,12,15]
ar1 = np.array(list1)
ar1[0] = 100
ar1[2] = 25
print(ar1)
print("Length of array = {}".format(len(ar1)))


[100   4  25  10  12  15]
Length of array = 6


In [3]:
import numpy as np
list1 = [12,13,14]
ar1 = np.array(list1)
ar1[0] = 100
ar1[2] = 25
print(ar1)
print("Length of array = {}".format(len(ar1)))

[100  13  25]
Length of array = 3


In [5]:
import numpy as np
list1 = [10,20,25,30,35,40,45,50]
ar1 = np.array(list1)
ar1[0] = 100
ar1[2] = 25
print(ar1)
print("Length of array = {}".format(len(ar1)))

[100  20  25  30  35  40  45  50]
Length of array = 8


In [8]:
import numpy as np
list1 = [3,4,5,6]
arr = np.array(list1)
x=0
for m in arr:
    x=x+m
print(x)

18


In [9]:
import numpy as np
list1 = [10]
arr = np.array(list1)
x=0
for m in arr:
    x=x+m
print(x)

10


In [10]:
import numpy as np
list1 = [1,2,3,4,5]
arr = np.array(list1)
x=0
for m in arr:
    x=x+m
print(x)

15


In [11]:
import numpy as np
list1 = [4,8,10,12]
ar1=np.array(list1)
ar1=np.array(list1)
sum_ar1 = np.sum(ar1)
print("Sum of array = {}".format(sum_ar1))


Sum of array = 34


In [12]:
import numpy as np
list1 = [1,2,3,4]
ar1=np.array(list1)
ar1=np.array(list1)
sum_ar1 = np.sum(ar1)
print("Sum of array = {}".format(sum_ar1))

Sum of array = 10


In [13]:
import numpy as np
list1 = [10]
ar1=np.array(list1)
ar1=np.array(list1)
sum_ar1 = np.sum(ar1)
print("Sum of array = {}".format(sum_ar1))

Sum of array = 10


In [14]:
import numpy as np
list1 = [3,6,12]
ar1 = np.array(list1)
mean_ar1 = np.mean(ar1)
print("Mean of array={}".format(mean_ar1))

Mean of array=7.0


In [15]:
import numpy as np
list1 = [12,13,14,17]
ar1 = np.array(list1)
mean_ar1 = np.mean(ar1)
print("Mean of array={}".format(mean_ar1))

Mean of array=14.0


In [16]:
import numpy as np
list1 = [10,20,30,40,50]
ar1 = np.array(list1)
mean_ar1 = np.mean(ar1)
print("Mean of array={}".format(mean_ar1))

Mean of array=30.0


In [17]:
import numpy as np
list1 = [3,6,12]
nums=np.array(list1)
min1 = np.min(nums)
max1= np.max(nums)
print("Min of array = {}".format(min1))
print("Max of array = {}".format(max1))

Min of array = 3
Max of array = 12


In [18]:
import numpy as np
list1 = [20,30,12,13,14,17]
nums=np.array(list1)
min1 = np.min(nums)
max1= np.max(nums)
print("Min of array = {}".format(min1))
print("Max of array = {}".format(max1))

Min of array = 12
Max of array = 30


In [19]:
import numpy as np
list1 = [4,8,2,4,6,7]
nums=np.array(list1)
min1 = np.min(nums)
max1= np.max(nums)
print("Min of array = {}".format(min1))
print("Max of array = {}".format(max1))

Min of array = 2
Max of array = 8


In [22]:
import numpy as np
list2=[2,5,10]
b=1
a=np.array([list2])
a=a+b
print(a)

[[ 3  6 11]]


In [23]:
import numpy as np
list2=[1,2,3,4]
b=3
a=np.array([list2])
a=a+b
print(a)

[[4 5 6 7]]


In [24]:
import numpy as np
list2=[20]
b=6
a=np.array([list2])
a=a+b
print(a)

[[26]]


In [25]:
import numpy as np
list2=[3,4,5,6]
b=1
a=np.array([list2])
a=a+3*b
print(a)

[[6 7 8 9]]


In [26]:
import numpy as np
list2=[1,2,3,4]
b=3
a=np.array([list2])
a=a+3*b
print(a)

[[10 11 12 13]]


In [27]:
import numpy as np
list2=[20]
b=6
a=np.array([list2])
a=a+3*b
print(a)

[[38]]


In [28]:
import numpy as np
list2=[1,2,3,4]
a=np.array([list2])
a=a*4
print(a)

[[ 4  8 12 16]]


In [29]:
import numpy as np
list2=[2,5]
a=np.array([list2])
a=a*4
print(a)

[[ 8 20]]


In [30]:
import numpy as np
list2=[11]
a=np.array([list2])
a=a*4
print(a)

[[44]]


In [31]:
import numpy as np
list2=[3,6,9]
x=3
a=np.array([list2])
a=a/x
print(a)

[[1. 2. 3.]]


In [32]:
import numpy as np
list2=[2,4,8,10]
x=2
a=np.array([list2])
a=a/x
print(a)

[[1. 2. 4. 5.]]


In [33]:
import numpy as np
list2=[25,10,10,20,30]
x=5
a=np.array([list2])
a=a/x
print(a)

[[5. 2. 2. 4. 6.]]


In [35]:
import numpy as np
list2=[1,2,3,4]
a=np.array([list2])
a=a**2
print(a)

[[ 1  4  9 16]]


In [36]:
import numpy as np
list2=[2,5]
a=np.array([list2])
a=a**2
print(a)

[[ 4 25]]


In [37]:
import numpy as np
list2=[11]
a=np.array([list2])
a=a**2
print(a)

[[121]]


In [42]:
import numpy as np
list2=[1,3,5,2]
a=np.array([list2])
m=2
n=6
p=5
a=a+2*m
print(a)
a=a*p
print(a)
a=a-n
print(a)

[[5 7 9 6]]
[[25 35 45 30]]
[[19 29 39 24]]


In [41]:
import numpy as np
list2=[4]
a=np.array([list2])
m=2
n=6
p=5
a=a+2*m
a=a*p
a=a-n
print(a)

[[34]]


In [1]:
import numpy as np
list1=[2,3,4,5]
list2=[1,2,1,2]
x1=np.array(list1)
x2=np.array(list2)
x3=x1+x2
print(x3)

[3 5 5 7]


In [2]:
import numpy as np
list1=[2,5]
list2=[1,4]
x1=np.array(list1)
x2=np.array(list2)
x3=x1+x2
print(x3)

[3 9]


In [3]:
import numpy as np
list1=[6]
list2=[3]
x1=np.array(list1)
x2=np.array(list2)
x3=x1+x2
print(x3)

[9]


In [4]:
import numpy as np
list1=[2,3,4,5]
list2=[1,2,1,2]
x1=np.array(list1)
x2=np.array(list2)
x3=x1-x2
print(x3)

[1 1 3 3]


In [5]:
import numpy as np
list1=[2,5]
list2=[1,4]
x1=np.array(list1)
x2=np.array(list2)
x3=x1-x2
print(x3)

[1 1]


In [6]:
import numpy as np
list1=[6]
list2=[3]
x1=np.array(list1)
x2=np.array(list2)
x3=x1-x2
print(x3)

[3]


In [7]:
import numpy as np
list1=[2,3,4,5]
list2=[2,1,1,1]
x1=np.array(list1)
x2=np.array(list2)
x3=x1*x2
print(x3)

[4 3 4 5]


In [8]:
import numpy as np
list1=[2,3]
list2=[4,5]
x1=np.array(list1)
x2=np.array(list2)
x3=x1*x2
print(x3)

[ 8 15]


In [9]:
import numpy as np
list1=[6]
list2=[3]
x1=np.array(list1)
x2=np.array(list2)
x3=x1*x2
print(x3)

[18]


In [10]:
import numpy as np
list1=[2,8,4,12]
list2=[1,2,1,2]
x1=np.array(list1)
x2=np.array(list2)
x3=x1/x2
print(x3)

[2. 4. 4. 6.]


In [11]:
import numpy as np
list1=[2,12]
list2=[1,4]
x1=np.array(list1)
x2=np.array(list2)
x3=x1/x2
print(x3)

[2. 3.]


In [12]:
import numpy as np
list1=[6]
list2=[3]
x1=np.array(list1)
x2=np.array(list2)
x3=x1/x2
print(x3)

[2.]


In [13]:
import numpy as np
list1=[2,3,4,5]
list2=[1,2,1,2]
x1=np.array(list1)
x2=np.array(list2)
x3=x1**x2
print(x3)

[ 2  9  4 25]


In [14]:
import numpy as np
list1=[2,5]
list2=[1,4]
x1=np.array(list1)
x2=np.array(list2)
x3=x1**x2
print(x3)

[  2 625]


In [15]:
import numpy as np
list1=[6]
list2=[3]
x1=np.array(list1)
x2=np.array(list2)
x3=x1**x2
print(x3)

[216]


In [16]:
import numpy as np
list1=[1,2,3,4,5]
list2=[1,2,1,2,1]
list3=[2,3,4,5,6]
x1=np.array(list1)
x2=np.array(list2)
x3=np.array(list3)
y1=x1+2*x2
print(y1)
y2=y1-x3
print(y2)
y3=y2*x1
print(y3)
y4=y3**x2
print(y4)

[3 6 5 8 7]
[1 3 1 3 1]
[ 1  6  3 12  5]
[  1  36   3 144   5]


In [2]:
import numpy as np 
n = 5
list1 = []
for i in range(1,n+1):
    list1.append(i)
print(list1)
ar1 = np.array(list1)
mean_ar1 = np.mean(ar1)
print("mean of numbers = {}".format(mean_ar1))
std_ar1 = np.std(ar1)
print("Standard deviation of numbers = {}".format(std_ar1))

[1, 2, 3, 4, 5]
mean of numbers = 3.0
Standard deviation of numbers = 1.4142135623730951


In [3]:
import numpy as np 
n = 10
list1 = []
for i in range(1,n+1):
    list1.append(i)
print(list1)
ar1 = np.array(list1)
mean_ar1 = np.mean(ar1)
print("mean of numbers = {}".format(mean_ar1))
std_ar1 = np.std(ar1)
print("Standard deviation of numbers = {}".format(std_ar1))


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
mean of numbers = 5.5
Standard deviation of numbers = 2.8722813232690143


In [4]:
import numpy as np 
n = 3
list1 = []
for i in range(1,n+1):
    list1.append(i)
print(list1)
ar1 = np.array(list1)
mean_ar1 = np.mean(ar1)
print("mean of numbers = {}".format(mean_ar1))
std_ar1 = np.std(ar1)
print("Standard deviation of numbers = {}".format(std_ar1))

[1, 2, 3]
mean of numbers = 2.0
Standard deviation of numbers = 0.816496580927726


In [5]:
import numpy as np 
list1=[34,33,29,51,44]
list2=[]
n=len(list1)
for i in range(0,n):
    b=list1[i]
    c=b-10
    list2.append(c)
print(list2)

[24, 23, 19, 41, 34]


In [6]:
import numpy as np 
list1=[34,33,29,51,44]
x1=np.array(list1)
y1=x1-10
print(y1)


[24 23 19 41 34]


In [7]:
import numpy as np 
list1=[44]
x1=np.array(list1)
y1=x1-10
print(y1)


[34]


In [8]:
import numpy as np 
list1=[11,11,11,11]
x1=np.array(list1)
y1=x1-10
print(y1)

[1 1 1 1]


In [11]:
import numpy as np 
list1=[2,3,5]
list2=[10,15,30]
l=0
p=0
n=len(list1)
for i in range(0,n):
    b=list1[i]
    l=b+l
    m=list1[i]*list2[i]
    p=p+m
print("Value = {}".format(p))
print("Number of products sold = {}".format(l))

Value = 215
Number of products sold = 10


In [10]:
import numpy as np 
list1=[2,10]
list2=[5,6]
l=0
p=0
n=len(list1)
for i in range(0,n):
    b=list1[i]
    l=b+l
    m=list1[i]*list2[i]
    p=p+m
print("Value = {}".format(p))
print("Number of products sold = {}".format(l))

Value = 70
Number of products sold = 12


In [12]:
import numpy as np 
list1=[1,1,2,2,2]
list2=[2,3,4,5,6]
l=0
p=0
n=len(list1)
for i in range(0,n):
    b=list1[i]
    l=b+l
    m=list1[i]*list2[i]
    p=p+m
print("Value = {}".format(p))
print("Number of products sold = {}".format(l))

Value = 35
Number of products sold = 8
