In [1]:
import numpy as np
list1 = [1,2,3,4]
ar1 = np.array(list1)
print(ar1)

[1 2 3 4]


In [2]:
import numpy as np
list1 = [1,2,3,4]
ar1 = np.array(list1)
print(ar1)
ar1[0] = 7
print(ar1)

[1 2 3 4]
[7 2 3 4]


In [3]:
import numpy as np
list1 = [1,2,3,4]
ar1 = np.array(list1)
print(ar1)
ar1[0] = 7
print(ar1)
ar1[1] = 6
print(ar1)

[1 2 3 4]
[7 2 3 4]
[7 6 3 4]


In [4]:
import numpy as np
list1 = [1,2,3,4]
ar1 = np.array(list1)
print(ar1)
ar1[0] = 7
print(ar1)
ar1[1] = 6
print(ar1)
print("Length of the numpy array = {}".format(len(ar1)))

[1 2 3 4]
[7 2 3 4]
[7 6 3 4]
Length of the numpy array = 4


In [6]:
import numpy as np
list1 = [1,2,3,5]
ar1 = np.array(list1)
print(ar1)
print("Length of the numpy array = {}".format(len(ar1)))
for i in ar1 :
    print(i)

[1 2 3 5]
Length of the numpy array = 4
1
2
3
5


In [1]:
import numpy as np
list1 = [1,2,3,5]
ar1 = np.array(list1)
sum_ar1 = np.sum(ar1)
print("Sum of numbers = {}".format(sum_ar1))

Sum of numbers = 11


In [2]:
import numpy as np
list1 = [1,2,3,5]
ar1 = np.array(list1)
sum_ar1 = np.sum(ar1)
print("Sum of numbers = {}".format(sum_ar1))
mean_ar1 = np.mean(ar1)
print("mean of numbers = {}".format(mean_ar1))

Sum of numbers = 11
mean of numbers = 2.75


In [4]:
import numpy as np
list1 = [1,2,3,4]
ar1 = np.array(list1)
sum_ar1 = np.sum(ar1)
print("Sum of numbers = {}".format(sum_ar1))
mean_ar1 = np.mean(ar1)
print("mean of numbers = {}".format(mean_ar1))
std_ar1 = np.std(ar1)
print("Standard deviation of numbers = {}".format(std_ar1))


Sum of numbers = 10
mean of numbers = 2.5
Standard deviation of numbers = 1.118033988749895


In [5]:
import numpy as np
list1 = [1,2,3,4]
ar1 = np.array(list1)
sum_ar1 = np.sum(ar1)
print("Sum of numbers = {}".format(sum_ar1))
mean_ar1 = np.mean(ar1)
print("mean of numbers = {}".format(mean_ar1))
std_ar1 = np.std(ar1)
print("Standard deviation of numbers = {}".format(std_ar1))
print("Max of numbers = {}".format(np.max(ar1)))


Sum of numbers = 10
mean of numbers = 2.5
Standard deviation of numbers = 1.118033988749895
Max of numbers = 4


In [6]:
import numpy as np
list1 = [1,2,3,4]
ar1 = np.array(list1)
sum_ar1 = np.sum(ar1)
print("Sum of numbers = {}".format(sum_ar1))
mean_ar1 = np.mean(ar1)
print("mean of numbers = {}".format(mean_ar1))
std_ar1 = np.std(ar1)
print("Standard deviation of numbers = {}".format(std_ar1))
print("Max of numbers = {}".format(np.max(ar1)))
print("Min of numbers = {}".format(np.min(ar1)))

Sum of numbers = 10
mean of numbers = 2.5
Standard deviation of numbers = 1.118033988749895
Max of numbers = 4
Min of numbers = 1


In [7]:
import numpy as np
list1 = [2,4,6,8,10]
ar1 = np.array(list1)
sum_ar1 = np.sum(ar1)
print("Sum of numbers = {}".format(sum_ar1))
mean_ar1 = np.mean(ar1)
print("mean of numbers = {}".format(mean_ar1))
std_ar1 = np.std(ar1)
print("Standard deviation of numbers = {}".format(std_ar1))
print("Max of numbers = {}".format(np.max(ar1)))
print("Min of numbers = {}".format(np.min(ar1)))

Sum of numbers = 30
mean of numbers = 6.0
Standard deviation of numbers = 2.8284271247461903
Max of numbers = 10
Min of numbers = 2


In [12]:
import numpy as np
a= np.array([1,2,3,4])
b=a+2
print(b)
b = a-1
print(b)
b=a*2
print(b)
b=a/2
print(b)
b=a**3
print(b)

[3 4 5 6]
[0 1 2 3]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  8 27 64]


In [13]:
import numpy as np
a= np.array([1,2,3,4])
a=a+2
print(a)
a = a-1
print(a)
a=a*2
print(a)
a=a/2
print(a)
a=a**3
print(a)

[3 4 5 6]
[2 3 4 5]
[ 4  6  8 10]
[2. 3. 4. 5.]
[  8.  27.  64. 125.]


In [1]:
import numpy as np
a = np.array([3,4,5,6])
b = np.array([1,2,3,4])
c=a+b
print(c)

[ 4  6  8 10]


In [2]:
import numpy as np
a = np.array([3,4,5,6])
b = np.array([1,2,3,4])
c=a+b
print(c)
c=a-b
print(c)
c=a*b
print(c)
c=a/b
print(c)
c=a**b
print(c)

[ 4  6  8 10]
[2 2 2 2]
[ 3  8 15 24]
[3.         2.         1.66666667 1.5       ]
[   3   16  125 1296]


In [3]:
import numpy as np
a = np.array([3,4,5,6])
m1 = np.mean(a)
s1=np.std(a)
print("Mean of a={}".format(m1),"Standard Deviation of a={}".format(s1))

Mean of a=4.5 Standard Deviation of a=1.118033988749895


In [4]:
import numpy as np
a = np.array([3,4,5,6])
m1 = np.mean(a)
s1=np.std(a)
print("Mean of a={}".format(m1),"Standard Deviation of a={}".format(s1))
b=a-m1
m2=np.mean(b)
s2=np.std(b)
print("Mean of b={}".format(m2),"Standard Deviation of b={}".format(s2))

Mean of a=4.5 Standard Deviation of a=1.118033988749895
Mean of b=0.0 Standard Deviation of b=1.118033988749895


In [5]:
import numpy as np
a = np.array([3,4,5,6])
m1 = np.mean(a)
s1=np.std(a)
print("Mean of a={}".format(m1),"Standard Deviation of a={}".format(s1))
b=(a-m1)/s1
m2=np.mean(b)
s2=np.std(b)
print("Mean of b={}".format(m2),"Standard Deviation of b={}".format(s2))

Mean of a=4.5 Standard Deviation of a=1.118033988749895
Mean of b=0.0 Standard Deviation of b=1.0
